server:
  port: 8881
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bird?serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver   #驱动引擎

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  thymeleaf:
    check-template: false
    check-template-location: false




#mybatis:
#  #config-locations: mybatis/mybatis-config.xml
#  mapper-locations: com/guxf/mapper/*.xml
#  type-aliases-package: com.javaweb.mapper.AuthorMapper